---

- name: Assert download config is valid
  ansible.builtin.assert:
    that:
      - oracle_jdbc_connector_artifact is not none
        or (oracle_jdbc_connector_user is not none
            and oracle_jdbc_connector_password is not none)
  tags:
    - role::oracle_jdbc_connector::check
