---
# Role check tasks

- block:
    - name: assert download config is valid
      assert:
        that:
          - oracle_jdbc_connector_artifact is none
            or (oracle_jdbc_connector_user is not none
                and oracle_jdbc_connector_password is not none)
  tags:
    - role::oracle_jdbc_connector
    - role::oracle_jdbc_connector::check
