---
# Role check tasks

- block:
    - name: assert platform is supported
      assert:
        that:
          - distribution in oracle_jdbc_connector_supported_distributions
          - >-
            ansible_facts.distribution_version
            is version(oracle_jdbc_connector_supported_versions[distribution],
                       ">=")

    - name: check if oracle jdbc connector is installed
      stat:
        path: "{{ oracle_jdbc_connector_jar_path }}"
      register: oracle_jdbc_connector_jar_check_result
  vars:
    distribution: "{{ ansible_facts.distribution | lower }}"
  tags:
    - role::oracle_jdbc_connector
    - role::oracle_jdbc_connector::check
