---
# Role cleanup maven tasks

- name: Remove maven temporary download directory
  file:
    path: "{{ oracle_jdbc_connector_download_dest }}/.m2"
    state: absent

- name: Remove maven wagon required by oracle repository
  file:
    path: "{{ oracle_jdbc_connector_maven_ext_path }}"
    state: absent
