---
# Role cleanup tasks

- block:
    - block:
        - name: Remove maven temporary download directory
          file:
            path: "{{ oracle_jdbc_connector_download_dest }}/.m2"
            state: absent
          when: oracle_jdbc_connector_remove_artifact | bool

        - name: Remove maven wagon required by oracle repository
          file:
            path: "{{ oracle_jdbc_connector_maven_ext_path }}"
            state: absent
      when: oracle_jdbc_connector_artifact is none

    - block:
        - name: Remove oracle jdbc connector unarchive directory
          file:
            path: "{{ oracle_jdbc_connector_artifact_unarchive_dir }}"
            state: absent

        - name: Remove oracle jdbc connector artifact
          file:
            path: "{{ oracle_jdbc_connector_artifact_path }}"
            state: absent
          when: oracle_jdbc_connector_remove_artifact | bool
      when:
        - oracle_jdbc_connector_artifact is not none
        - oracle_jdbc_connector_install_required | bool
  tags:
    - role::oracle_jdbc_connector
    - role::oracle_jdbc_connector::cleanup
