---
# Role cleanup tasks

- include: cleanup_maven.yml
  when: oracle_jdbc_connector_artifact is none

- include_tasks: artifact.yml
  when: oracle_jdbc_connector_artifact is not none
  vars:
    oracle_jdbc_connector_state: absent

- name: Cleanup oracle jdbc connector components
  file:
    path: "{{ mysql_jdbc_connector_item }}"
    state: absent
  loop: >-
    {{ oracle_jdbc_connector_search_result.files
       | map(attribute="path")
       | list
       | difference(lookup('template', 'components.yml.j2')
                    | from_yaml
                    | map(attribute="dest")
                    | list) }}
  loop_control:
    loop_var: oracle_jdbc_connector_item
