---
# Role cleanup tasks

- block:
    - name: remove maven temporary download directory
      file:
        path: "{{ oracle_jdbc_connector_download_dest }}/.m2"
        state: absent

    - name: remove maven wagon required by oracle repository
      file:
        path: "{{ oracle_jdbc_connector_maven.ext_path }}"
        state: absent
  when:
    - oracle_jdbc_connector_artifact is undefined
  tags:
    - role::oracle_jdbc_connector
    - role::oracle_jdbc_connector::cleanup
