---

- name: Download oracle jdbc connector artifact
  block:
    - name: Download oracle jdbc connector maven artifact
      ansible.builtin.include_tasks: maven.yml
      when: oracle_jdbc_connector_artifact is none

    - name: Download oracle jdbc connector artifact
      ansible.builtin.include_tasks: artifact.yml
      when: oracle_jdbc_connector_artifact is not none
      vars:
        oracle_jdbc_connector_state: present
  when:
    - oracle_jdbc_connector_state == "present"
    - oracle_jdbc_connector_install_required | bool
  environment: "{{ proxy_client_environment }}"
  tags:
    - role::oracle_jdbc_connector
    - role::oracle_jdbc_connector::download
