---

- name: Setp oracle jdbc connector local facts
  block:
    - name: Perform oracle jdbc connector local facts setup
      when: oracle_jdbc_connector_state == "present"
      block:
        - name: Setup oracle jdbc connector components path facts
          ansible.builtin.set_fact:
            "oracle_jdbc_connector_{{ item }}_jar_path": >-
              {{ oracle_jdbc_connector_dir }}/{{ item }}.jar
          loop: "{{ oracle_jdbc_connector_components }}"
          loop_control:
            label: "oracle_jdbc_connector_{{ item }}_jar_path"

        - name: Create local facts directory
          ansible.builtin.file:
            path: /etc/ansible/facts.d
            state: directory
            mode: 0755

        - name: Setup oracle jdbc connector local fact
          ansible.builtin.template:
            src: connector.fact.j2
            dest: /etc/ansible/facts.d/oracle_jdbc_connector.fact
            mode: 0640

    - name: Remove oracle jdbc connector local fact
      when: oracle_jdbc_connector_state == "absent"
      ansible.builtin.file:
        path: /etc/ansible/facts.d/oracle_jdbc_connector.fact
        state: absent
  tags:
    - role::oracle_jdbc_connector::facts