---
# Role facts tasks

- block:
    - name: Setup oracle jdbc connector components path facts
      set_fact:
         "oracle_jdbc_connector_{{ item }}_jar_path": >-
          {{ oracle_jdbc_connector_dir }}/{{ item }}.jar
      loop: "{{ oracle_jdbc_connector_components }}"
      loop_control:
        label: "oracle_jdbc_connector_{{ item }}_jar_path"

    - name: Check if oracle jdbc connector components are installed
      stat:
        path: >-
          {{ lookup("vars", "oracle_jdbc_connector_" + item + "_jar_path") }}
      register: oracle_jdbc_connector_jar_check_result
      loop: "{{ oracle_jdbc_connector_components }}"

    - name: Setup fact indicating if install is required
      set_fact:
        oracle_jdbc_connector_install_required: >-
          {{ oracle_jdbc_connector_jar_check_result.results
             | selectattr("stat.exists", "equalto", false)
             | list
             | length > 0
             and oracle_jdbc_connector_state == "present" }}
  tags:
    - role::oracle_jdbc_connector
    - role::oracle_jdbc_connector::facts
