---
# Role facts tasks

- block:
    - when: oracle_jdbc_connector_state == "present"
      block:
        - name: Setup oracle jdbc connector components path facts
          set_fact:
             "oracle_jdbc_connector_{{ item }}_jar_path": >-
              {{ oracle_jdbc_connector_dir }}/{{ item }}.jar
          loop: "{{ oracle_jdbc_connector_components }}"
          loop_control:
            label: "oracle_jdbc_connector_{{ item }}_jar_path"

        - name: Create local facts directory
          file:
            path: /etc/ansible/facts.d
            state: directory

        - name: Setup oracle jdbc connector local fact
          template:
            src: connector.fact.j2
            dest: /etc/ansible/facts.d/oracle_jdbc_connector.fact
            mode: 0640

    - when: oracle_jdbc_connector_state == "present"
      name: Remove oracle jdbc connector local fact
      file:
        path: /etc/ansible/facts.d/oracle_jdbc_connector.fact
        state: absent
  tags:
    - role::oracle_jdbc_connector::facts
