---
# Role install tasks

- block:
    - name: create oracle jdbc connector destination directory
      file:
        path: "{{ oracle_jdbc_connector_dir }}"
        state: directory

    - name: extract oracle jdbc connector artifact
      unarchive:
        src: "{{ oracle_jdbc_connector_artifact_path }}"
        dest: "{{ oracle_jdbc_connector_download_dest }}"
        copy: no
        list_files: yes
      register: oracle_jdbc_connector_unarchive_result
      when:
        - oracle_jdbc_connector_artifact is defined
        - oracle_jdbc_connector_install_required

    - name: install oracle jdbc connector component
      copy:
        src: "{{ jar_path }}"
        dest: "{{ oracle_jdbc_connector_dir }}/{{ item }}.jar"
        remote_src: yes
      loop: "{{ oracle_jdbc_connector_components }}"
      vars:
        maven_jar_path: >-
          {{ oracle_jdbc_connector_download_dest
             + "/.m2/com/oracle/jdbc/"
             + item
             + "/"
             + oracle_jdbc_connector_version
             + "/"
             + item
             + "-"
             + oracle_jdbc_connector_version
             + ".jar"
             if oracle_jdbc_connector_artifact is undefined
             else "" }}
        artifact_jar_path: >-
          {{ oracle_jdbc_connector_artifact_unarchive_dir
             + "/"
             + item
             + ".jar"
             if oracle_jdbc_connector_artifact is defined
             else "" }}
        jar_path: >-
          {{ artifact_jar_path
             if oracle_jdbc_connector_artifact is defined
             else maven_jar_path }}
  when:
    - oracle_jdbc_connector_state == "present"
    - oracle_jdbc_connector_install_required
  tags:
    - role::oracle_jdbc_connector
    - role::oracle_jdbc_connector::install
