---
# Role install tasks

- block:
    - name: create oracle jdbc connector destination directory
      file:
        path: "{{ oracle_jdbc_connector_dir }}"
        state: directory

    - name: install oracle jdbc connector
      copy:
        src: "{{ oracle_jdbc_connector_package }}"
        dest: "{{ oracle_jdbc_connector_dir }}"
        remote_src: yes
  when:
    - oracle_jdbc_connector_state == "present"
    - >-
      (oracle_jdbc_connector_jar_check_result is defined
      and not oracle_jdbc_connector_jar_check_result.stat.exists)
      or oracle_jdbc_connector_jar_check_result is undefined
  tags:
    - role::oracle_jdbc_connector
    - role::oracle_jdbc_connector::install
