---

- name: Download oracle jdbc connector from maven
  block:
    - name: Download maven wagon required by oracle repository
      ansible.builtin.get_url:
        url: "{{ oracle_jdbc_connector_maven_wagon_url }}"
        dest: "{{ oracle_jdbc_connector_maven_ext_path }}"
        mode: 0640
      register: oracle_jdbc_connector_wagon_download_result

    - name: Generate maven master encrypted password
      ansible.builtin.command: >-
        mvn --encrypt-master-password {{ oracle_jdbc_connector_password }}
      changed_when: no
      register: oracle_jdbc_connector_maven_master_key_result

    - name: Setup maven security settings file
      ansible.builtin.template:
        src: security-settings.xml.j2
        dest: >-
          {{ oracle_jdbc_connector_download_dest }}/security-settings.xml
        mode: 0600

    - name: Encrypt oracle maven repository password
      ansible.builtin.command: >-
        mvn
        -Dsettings.security={{ oracle_jdbc_connector_download_dest
                               + "/security-settings.xml "
                               + "--encrypt-password "
                               + oracle_jdbc_connector_password }}
      changed_when: no
      register: oracle_jdbc_connector_maven_repo_key_result

    - name: Setup maven settings file
      ansible.builtin.template:
        src: settings.xml.j2
        dest: "{{ oracle_jdbc_connector_download_dest }}/settings.xml"
        mode: 0755

    - name: Setup maven project file
      ansible.builtin.template:
        src: pom.xml.j2
        dest: "{{ oracle_jdbc_connector_download_dest }}/pom.xml"
        mode: 0755

    - name: Download oracle jdbc connector from maven repository
      ansible.builtin.command: >-
        mvn
        -Dsettings.security={{ oracle_jdbc_connector_download_dest
                               + "/security-settings.xml "
                               + "-s "
                               + oracle_jdbc_connector_download_dest
                               + "/settings.xml compile" }}
      args:
        chdir: "{{ oracle_jdbc_connector_download_dest }}"
      when: yes
      register: oracle_jdbc_connector_maven_compile_result
  environment: "{{ proxy_client_environment }}"
  tags:
    - role::oracle_jdbc_connector
    - role::oracle_jdbc_connector::download