---
# Role required packages tasks

- block:
    - name: install required operating system packages
      package:
        name: "{{ item }}"
        state: present
      loop: >-
        {{ oracle_jdbc_connector_os_packages[distro_packages_key] }}

    - name: install required python packages
      pip:
        name: "{{ item }}"
        state: present
        extra_args: "{{ oracle_jdbc_connector_pip_extra_args }}"
      loop: >-
        {{ oracle_jdbc_connector_python_packages[distro_packages_key] }}
  when: oracle_jdbc_connector_artifact is undefined
  environment: "{{ oracle_jdbc_connector_http_proxy_environment }}"
  vars:
    distro_packages_key: >-
      {{ ansible_facts.distribution
         | lower
         + "_" + ansible_facts.distribution_major_version }}
  tags:
    - role::oracle_jdbc_connector
    - role::oracle_jdbc_connector::packages
