---

- name: Uninstall oracle jdbc connector
  ansible.builtin.file:
    path: "{{ oracle_jdbc_connector_dir }}/{{ item }}.jar"
    state: absent
  loop: "{{ oracle_jdbc_connector_components }}"
  tags:
    - role::oracle_jdbc_connector::uninstall
