---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Check oracle connector component
      stat:
        path: "{{ oracle_jdbc_connector_dir }}/{{ item }}.jar"
      loop: "{{ oracle_jdbc_connector_components }}"
      register: check_install_result

    - name: Check that oracle jdbc connector was installed
      assert:
        that:
          - >-
            check_install_result.results
            | selectattr("stat.exists", "equalto", "false")
            | list
            | length == 0
  vars:
    ansible_python_interpreter: >-
      {{ (inventory_hostname in groups.molecule_hosts_centos_7)
         | ternary("/usr/bin/python", "/usr/bin/python3") }}
